spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/u_give
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/u_give
    username: kate
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Flyway Scripts
    validate-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    out-of-order: true
    clean-on-validation-error: false
    ignore-migration-patterns: '*:ignored'

  mail:
    host: smtp.gmail.com
    port: 587
    username: ugive.demo.project23@gmail.com
    password: oqvpmtzwikzjyite
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

application:
  security:
    jwt:
      secret-key: 4IHJU69VRDFDC5DG954F6800hg6vy9GRFDf5
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days